
name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: python -m compileall .
      - name: Build Docker image
        run: docker build -t capstone-flask:${{ github.sha }} .
      # - name: Push to ACR (example - configure later)
      #   run: |
      #     echo "Login & push steps go here"
